service: serverless-users-api-microsservice
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    NODE_OPTIONS: --enable-source-maps --stack-trace-limit=1000 --experimental-modules --es-module-specifier-resolution=node

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'

plugins:
 - serverless-plugin-typescript